language: node_js
node_js:
    - 14
script:
    - npm run lint
    - npm run test:coverage
deploy:
    provider: heroku
    api_key:
        secure: ${{ secrets.HEROKU_API_KEY }}
    app: Book-Library-API
    on:
        branch: main
        repo: RogerioSobrinho/Book-Library-API
