# docker-compose.yml
version: '3'
services:
    api:
        restart: always
        container_name: booklibrary-api
        # volumes:
        #     - .:/usr/src/app/
        #     - /usr/src/app/node_modules
        environment:
            DB_HOST: db
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 3000:3000
        depends_on:
            - db
    db:
        container_name: booklibrary-db
        image: 'postgres'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: magical_password
            POSTGRES_DB: book_database
        volumes:
            - /private/var/lib/postgresql:/var/lib/postgresql
        ports:
            - '5432:5432'
